// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Comment struct {
	CommentID int64
	PostID    pgtype.Int8
	UserID    pgtype.Int8
	Body      string
	CreatedAt pgtype.Timestamp
	EditedAt  pgtype.Timestamp
}

type Post struct {
	PostID    int64
	UserID    pgtype.Int8
	Title     string
	CreatedAt pgtype.Timestamp
}

type User struct {
	UserID          int64
	Name            string
	PasswordHash    string
	IsAdministrator pgtype.Bool
	CreatedOn       pgtype.Date
}
